version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./backend:/app/backend
    command: npm run dev
    networks:
      - knostic-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: npm run dev
    depends_on:
      - backend
    networks:
      - knostic-network

  # Development database (optional - for future use)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=knostic
      - POSTGRES_USER=knostic
      - POSTGRES_PASSWORD=knostic123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - knostic-network

volumes:
  postgres_data:

networks:
  knostic-network:
    driver: bridge
